name: Build Frontend and Backend Containers

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/*'

# Set up permissions for deploying with secretless Azure federated credentials
# https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Clinux#set-up-azure-login-with-openid-connect-authentication
permissions:
  id-token: write
  contents: read
  actions: read
  checks: read
  deployments: read
  issues: read
  discussions: read
  packages: read
  pages: read
  pull-requests: read
  repository-projects: read
  security-events: read
  statuses: read

env:
  docker_reponame: "welasco"

jobs:
  ########################
  # Frontend Container Job
  ########################
  docker_build_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate tags frontend
        id: docker_tags_frontend
        uses: greboid/docker-tags-action@v1
        with:
          repository: "${{ env.docker_reponame }}/assistants-api-playground-frontend"

      - name: Print tags for Image frontend
        run: echo ${{ steps.docker_tags_frontend.outputs.tags }}

      - name: Build and push linux/amd64 frontend image
        id: docker_build_amd64_frontend
        uses: docker/build-push-action@v5
        with:
          context: ./src/frontend/
          file: ./src/frontend/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.docker_tags_frontend.outputs.tags }}

  ########################
  # Backend Container Job
  ########################
  docker_build_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate tags backend
        id: docker_tags_backend
        uses: greboid/docker-tags-action@v1
        with:
          repository: "${{ env.docker_reponame }}/assistants-api-playground-backend"

      - name: Print tags for Image backend
        run: echo ${{ steps.docker_tags_backend.outputs.tags }}

      - name: Build and push linux/amd64 frontend image
        id: docker_build_amd64_backend
        uses: docker/build-push-action@v5
        with:
          context: ./src/backend/
          file: ./src/backend/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.docker_tags_backend.outputs.tags }}